version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: "user"
      RABBITMQ_DEFAULT_PASS: "password"
    ports:
      - "15672:15672"  # Management interface
      - "5672:5672"    # Application communication
    networks:
      - inventory_network

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "rootpassword"
      MYSQL_DATABASE: "inventory_db"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - inventory_network

  producer:
    build: ./producer
    depends_on:
      - rabbitmq
      - mysql
    networks:
      - inventory_network

  healthcheck:
    build: ./healthcheck
    depends_on:
      - rabbitmq
      - mysql
    networks:
      - inventory_network

  item_creation:
    build: ./item_creation
    depends_on:
      - rabbitmq
      - mysql
    networks:
      - inventory_network

  stock_management:
    build: ./stock_management
    depends_on:
      - rabbitmq
      - mysql
    networks:
      - inventory_network

  order_processing:
    build: ./order_processing
    depends_on:
      - rabbitmq
      - mysql
    networks:
      - inventory_network

networks:
  inventory_network:

volumes:
  mysql_data:
